In [6]:
from pybaseball import statcast_pitcher, playerid_lookup
player = playerid_lookup('webb','logan')

In [7]:
import pandas as pd

In [4]:
player

,name_last,name_first,key_mlbam,key_retro,key_bbref,key_fangraphs,mlb_played_first,mlb_played_last
0,webb,logan,657277,webbl001,webblo01,17995,2019.0,2026.0

In [5]:
combined_data.shape

NameError: name 'combined_data' is not defined

In [ ]:
df = pd.DataFrame(combined_data)
column_list = df.columns
print(f"There are {len(column_list)} columns and the first ten are {column_list[:20]}")
print(f"Events is {df['game_type'][:5]}")

In [ ]:
pitcher_id = playerid_lookup('crochet', ['key_mlbam'].iloc[0]

In [ ]:
combined_data['player_name'].unique()

In [ ]:
combined_data.groupby('player_name').size()

In [ ]:
combined_data['pitch_type'].value_counts()

In [ ]:
combined_data['release_speed'].describe()

In [ ]:
pitchers = [
    ('webb', 'logan'),
    ('lorenzen', 'michael'),
    ('yamamoto', 'yoshinobu'),
    ('gausman', 'kevin'),
    ('skenes', 'paul'),
    ('skubal', 'tarik'),
    ('chapman', 'aroldis'),
    ('doval', 'camilo'),
    ('crochet', 'garrett'),
    ('glasnow', 'tyler'),
]

all_data = []

for last_name, first_name in pitchers:
    lookup = playerid_lookup(last_name, first_name)
    pid = lookup['key_mlbam'].iloc[0]
    pitcher_data = statcast_pitcher('2025-04-01', '2025-10-31', pid)
    all_data.append(pitcher_data)

combined_data = pd.concat(all_data, ignore_index=True)

In [ ]:
combined_data[combined_data['release_speed'] <= 65]

In [ ]:
combined_data.isnull().sum().sort_values(ascending=False).head(10)

In [ ]:
pitcher_id

In [ ]:
data = statcast_pitcher('2024-04-01', '2024-04-30', pitcher_id)

In [ ]:
data_full_season = statcast_pitcher('2024-04-01', '2024-09-30', pitcher_id)

In [ ]:
data_full_season.shape

In [ ]:
data.shape

In [ ]:
data_full_season.head()

In [ ]:
data.head()

In [ ]:
pitchers = [
    ('webb', 'logan'),
    ('lorenzen', 'michael'),
    ('yamamoto', 'yoshinobu'),
    ('gausman', 'kevin'),
    ('skenes', 'paul'),
    ('skubal', 'tarik'),
    ('chapman', 'aroldis'),
    ('doval', 'camilo'),
    ('crochet', 'garrett'),
    ('glasnow', 'tyler'),
]

all_data = []

for last_name, first_name in pitchers:
    lookup = playerid_lookup(last_name, first_name)
    pid = lookup['key_mlbam'].iloc[0]
    pitcher_data = statcast_pitcher('2025-04-01', '2025-10-31', pid)
    all_data.append(pitcher_data)

combined_data = pd.concat(all_data, ignore_index=True)

print(combined_data.shape)
print(combined_data['player_name'].unique())
print(combined_data.groupby('player_name').size())

In [ ]:
combined_data.columns.tolist()

In [ ]:
combined_data.to_csv('combined_data_preview.csv', index=False)

In [8]:
pitchers = [
    ('cole', 'gerrit'), ('wheeler', 'zack'), ('strider', 'spencer'), ('burnes', 'corbin'),
    ('gausman', 'kevin'), ('glasnow', 'tyler'), ('webb', 'logan'), ('valdez', 'framber'),
    ('yamamoto', 'yoshinobu'), ('skenes', 'paul'), ('skubal', 'tarik'), ('crochet', 'garrett'),
    ('lorenzen', 'michael'), ('dunning', 'dane'), ('lugo', 'seth'), ('sale', 'chris'),
    ('peralta', 'freddy'), ('nola', 'aaron'), ('gray', 'sonny'), ('snell', 'blake'),
    ('gallen', 'zac'), ('fried', 'max'), ('miller', 'bryce'), ('greene', 'hunter'),
    ('suarez', 'ranger'), ('pivetta', 'nick'), ('berrios', 'jose'), ('kelly', 'merrill'),
    ('morton', 'charlie'), ('bieber', 'shane'), ('cease', 'dylan'), ('flaherty', 'jack'),
    ('bradish', 'kyle'), ('ober', 'bailey'), ('sanchez', 'cristopher'),
    ('clase', 'emmanuel'), ('chapman', 'aroldis'), ('doval', 'camilo'), ('fairbanks', 'pete'),
    ('hader', 'josh'), ('diaz', 'edwin'), ('williams', 'devin'), ('bautista', 'felix'),
    ('helsley', 'ryan'), ('miller', 'mason'), ('suarez', 'robert'), ('munoz', 'andres'),
    ('yates', 'kirby'), ('duran', 'jhoan'), ('ohtani', 'shohei'),
]

start_date = '2025-01-01'
end_date = '2026-07-28'

all_data = []
failed_pitchers = []

for last_name, first_name in pitchers:
    try:
        lookup = playerid_lookup(last_name, first_name)
        pid = lookup['key_mlbam'].iloc[0]
        pitcher_data = statcast_pitcher(start_date, end_date, pid)
        all_data.append(pitcher_data)
        print(f"Success: {first_name} {last_name} ({len(pitcher_data)} pitches)")
    except Exception as e:
        print(f"FAILED: {first_name} {last_name} - {e}")
        failed_pitchers.append((last_name, first_name))

combined_data = pd.concat(all_data, ignore_index=True)

Gathering Player Data
Success: gerrit cole (1203 pitches)
Gathering Player Data
Success: zack wheeler (4234 pitches)
Gathering Player Data
Success: spencer strider (3015 pitches)
Gathering Player Data
Success: corbin burnes (1300 pitches)
Gathering Player Data
Success: kevin gausman (5839 pitches)
Gathering Player Data
Success: tyler glasnow (2853 pitches)
Gathering Player Data
Success: logan webb (5413 pitches)
Gathering Player Data
Success: framber valdez (5249 pitches)
Gathering Player Data
Success: yoshinobu yamamoto (5538 pitches)
Gathering Player Data
Success: paul skenes (5459 pitches)
Gathering Player Data
Success: tarik skubal (4972 pitches)
Gathering Player Data
Success: garrett crochet (4286 pitches)
Gathering Player Data
Success: michael lorenzen (4649 pitches)
Gathering Player Data
Success: dane dunning (718 pitches)
Gathering Player Data
Success: seth lugo (4791 pitches)
Gathering Player Data
Success: chris sale (4393 pitches)
Gathering Player Data
Success: freddy peralta (5821 pitches)
Gathering Player Data
Success: aaron nola (3918 pitches)
Gathering Player Data
Success: sonny gray (4790 pitches)
Gathering Player Data
Success: blake snell (1744 pitches)
Gathering Player Data
Success: zac gallen (5136 pitches)
Gathering Player Data
Success: max fried (4778 pitches)
Gathering Player Data
Success: bryce miller (2964 pitches)
Gathering Player Data
Success: hunter greene (2557 pitches)
Gathering Player Data
Success: ranger suarez (4231 pitches)
Gathering Player Data
Success: nick pivetta (3661 pitches)
FAILED: jose berrios - single positional indexer is out-of-bounds
Gathering Player Data
Success: merrill kelly (4974 pitches)
Gathering Player Data
Success: charlie morton (0 pitches)
Gathering Player Data
Success: shane bieber (1516 pitches)
Gathering Player Data
Success: dylan cease (5553 pitches)
Gathering Player Data
Success: jack flaherty (5120 pitches)
Gathering Player Data
Success: kyle bradish (2675 pitches)
Gathering Player Data
Success: bailey ober (4148 pitches)
FAILED: cristopher sanchez - single positional indexer is out-of-bounds
Gathering Player Data
Success: emmanuel clase (868 pitches)
Gathering Player Data
Success: aroldis chapman (1772 pitches)
Gathering Player Data
Success: camilo doval (2010 pitches)
Gathering Player Data
Success: pete fairbanks (1776 pitches)
Gathering Player Data
Success: josh hader (1327 pitches)
FAILED: edwin diaz - single positional indexer is out-of-bounds
Gathering Player Data
Success: devin williams (2004 pitches)
FAILED: felix bautista - single positional indexer is out-of-bounds
Gathering Player Data
Success: ryan helsley (1472 pitches)
Gathering Player Data
Success: mason miller (1934 pitches)
Gathering Player Data
Success: robert suarez (1799 pitches)
FAILED: andres munoz - single positional indexer is out-of-bounds
Gathering Player Data
Success: kirby yates (1360 pitches)
FAILED: jhoan duran - single positional indexer is out-of-bounds
Gathering Player Data
Success: shohei ohtani (2571 pitches)

In [9]:
len(all_data)

44

In [10]:
all_data = [df for df in all_data if len(df) > 0]

In [11]:
new_pitchers = [
    ('castillo', 'luis'),
    ('berríos', 'josé'),
    ('sánchez', 'cristopher'),
    ('díaz', 'edwin'),
    ('bautista', 'félix'),
    ('muñoz', 'andrés'),
    ('durán', 'jhoan'),
]

for last_name, first_name in new_pitchers:
    try:
        lookup = playerid_lookup(last_name, first_name)
        pid = lookup['key_mlbam'].iloc[0]
        pitcher_data = statcast_pitcher(start_date, end_date, pid)
        all_data.append(pitcher_data)
        print(f"Success: {first_name} {last_name} ({len(pitcher_data)} pitches)")
    except Exception as e:
        print(f"FAILED: {first_name} {last_name} - {e}")
        failed_pitchers.append((last_name, first_name))

combined_data = pd.concat(all_data, ignore_index=True)

Gathering Player Data
Success: luis castillo (0 pitches)
Gathering Player Data
Success: josé berríos (3049 pitches)
Gathering Player Data
Success: cristopher sánchez (5498 pitches)
Gathering Player Data
Success: edwin díaz (1342 pitches)
Gathering Player Data
Success: félix bautista (736 pitches)
Gathering Player Data
Success: andrés muñoz (1998 pitches)
Gathering Player Data
Success: jhoan durán (1952 pitches)

In [12]:
playerid_lookup('castillo', 'luis')

,name_last,name_first,key_mlbam,key_retro,key_bbref,key_fangraphs,mlb_played_first,mlb_played_last
0,castillo,luis,112116,castl001,castilu01,513,1996.0,2010.0
1,castillo,luis,622379,castl004,castilu03,20638,2022.0,2025.0
2,castillo,luis,622491,castl003,castilu02,15689,2017.0,2026.0

In [13]:
castillo_data = statcast_pitcher(start_date, end_date, 622491)
all_data.append(castillo_data)
print(f"Success: luis castillo ({len(castillo_data)} pitches)")

Gathering Player Data
Success: luis castillo (5447 pitches)

In [14]:
combined_data = pd.concat(all_data, ignore_index=True)

In [15]:
combined_data['player_name'].nunique()

50

In [16]:
combined_data.groupby('player_name').size()

player_name
Bautista, Félix         736
Berríos, José          3049
Bieber, Shane          1516
Bradish, Kyle          2675
Burnes, Corbin         1300
Castillo, Luis         5447
Cease, Dylan           5553
Chapman, Aroldis       1772
Clase, Emmanuel         868
Cole, Gerrit           1203
Crochet, Garrett       4286
Doval, Camilo          2010
Dunning, Dane           718
Duran, Jhoan           1952
Díaz, Edwin            1342
Fairbanks, Pete        1776
Flaherty, Jack         5120
Fried, Max             4778
Gallen, Zac            5136
Gausman, Kevin         5839
Glasnow, Tyler         2853
Gray, Sonny            4790
Greene, Hunter         2557
Hader, Josh            1327
Helsley, Ryan          1472
Kelly, Merrill         4974
Lorenzen, Michael      4649
Lugo, Seth             4791
Miller, Bryce          2964
Miller, Mason          1934
Muñoz, Andrés          1998
Nola, Aaron            3918
Ober, Bailey           4148
Ohtani, Shohei         2571
Peralta, Freddy        5821
Pivetta, Nick          3661
Sale, Chris            4393
Skenes, Paul           5459
Skubal, Tarik          4972
Snell, Blake           1744
Strider, Spencer       3015
Suarez, Ranger         4231
Suarez, Robert         1799
Sánchez, Cristopher    5498
Valdez, Framber        5249
Webb, Logan            5413
Wheeler, Zack          4234
Williams, Devin        2004
Yamamoto, Yoshinobu    5538
Yates, Kirby           1360
dtype: int64

In [17]:
playerid_lookup('morton', 'charlie')

,name_last,name_first,key_mlbam,key_retro,key_bbref,key_fangraphs,mlb_played_first,mlb_played_last
0,morton,charlie,119424,mortc101,mortoch01,1009231,1882.0,1885.0
1,morton,charlie,450203,mortc002,mortoch02,4676,2008.0,2025.0

In [18]:
combined_data = pd.concat(all_data, ignore_index=True)
combined_data['player_name'].nunique()

50

In [19]:
combined_data.to_csv('data/raw/pitchers_2025_2026.csv', index=False)

OSError: Cannot save file into a non-existent directory: 'data/raw'

In [20]:
combined_data.to_csv('data/raw/pitchers_2025_2026.csv', index=False)

In [1]:
from pybaseball import statcast_pitcher, playerid_lookup

In [2]:
import pandas as pd

In [3]:
combined_data = pd.read_csv('data/raw/pitchers_2025_2026.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'data/raw/pitchers_2025_2026.csv'

In [4]:
pitchers = [
    ('cole', 'gerrit'), ('wheeler', 'zack'), ('strider', 'spencer'), ('burnes', 'corbin'),
    ('gausman', 'kevin'), ('glasnow', 'tyler'), ('webb', 'logan'), ('valdez', 'framber'),
    ('yamamoto', 'yoshinobu'), ('skenes', 'paul'), ('skubal', 'tarik'), ('crochet', 'garrett'),
    ('lorenzen', 'michael'), ('dunning', 'dane'), ('lugo', 'seth'), ('sale', 'chris'),
    ('peralta', 'freddy'), ('nola', 'aaron'), ('gray', 'sonny'), ('snell', 'blake'),
    ('gallen', 'zac'), ('fried', 'max'), ('miller', 'bryce'), ('greene', 'hunter'),
    ('suarez', 'ranger'), ('pivetta', 'nick'), ('kelly', 'merrill'),
    ('bieber', 'shane'), ('cease', 'dylan'), ('flaherty', 'jack'),
    ('bradish', 'kyle'), ('ober', 'bailey'), ('castillo', 'luis'),
    ('clase', 'emmanuel'), ('chapman', 'aroldis'), ('doval', 'camilo'), ('fairbanks', 'pete'),
    ('hader', 'josh'), ('williams', 'devin'),
    ('helsley', 'ryan'), ('miller', 'mason'), ('suarez', 'robert'),
    ('yates', 'kirby'), ('ohtani', 'shohei'),
    ('berríos', 'josé'), ('sánchez', 'cristopher'), ('díaz', 'edwin'),
    ('bautista', 'félix'), ('muñoz', 'andrés'), ('durán', 'jhoan'),
]

start_date = '2025-01-01'
end_date = '2026-07-28'

all_data = []
failed_pitchers = []

for last_name, first_name in pitchers:
    try:
        if last_name == 'castillo':
            pid = 622491  # hardcoded — fixes duplicate-name collision found earlier
        else:
            lookup = playerid_lookup(last_name, first_name)
            pid = lookup['key_mlbam'].iloc[0]
        pitcher_data = statcast_pitcher(start_date, end_date, pid)
        all_data.append(pitcher_data)
        print(f"Success: {first_name} {last_name} ({len(pitcher_data)} pitches)")
    except Exception as e:
        print(f"FAILED: {first_name} {last_name} - {e}")
        failed_pitchers.append((last_name, first_name))

combined_data = pd.concat(all_data, ignore_index=True)

Gathering player lookup table. This may take a moment.
Gathering Player Data
Success: gerrit cole (1203 pitches)
Gathering Player Data
Success: zack wheeler (4234 pitches)
Gathering Player Data
Success: spencer strider (3015 pitches)
Gathering Player Data
Success: corbin burnes (1300 pitches)
Gathering Player Data
Success: kevin gausman (5839 pitches)
Gathering Player Data
Success: tyler glasnow (2853 pitches)
Gathering Player Data
Success: logan webb (5413 pitches)
Gathering Player Data
Success: framber valdez (5249 pitches)
Gathering Player Data
Success: yoshinobu yamamoto (5538 pitches)
Gathering Player Data
Success: paul skenes (5459 pitches)
Gathering Player Data
Success: tarik skubal (4972 pitches)
Gathering Player Data
Success: garrett crochet (4286 pitches)
Gathering Player Data
Success: michael lorenzen (4649 pitches)
Gathering Player Data
Success: dane dunning (718 pitches)
Gathering Player Data
Success: seth lugo (4791 pitches)
Gathering Player Data
Success: chris sale (4393 pitches)
Gathering Player Data
Success: freddy peralta (5821 pitches)
Gathering Player Data
Success: aaron nola (3918 pitches)
Gathering Player Data
Success: sonny gray (4790 pitches)
Gathering Player Data
Success: blake snell (1744 pitches)
Gathering Player Data
Success: zac gallen (5136 pitches)
Gathering Player Data
Success: max fried (4778 pitches)
Gathering Player Data
Success: bryce miller (2964 pitches)
Gathering Player Data
Success: hunter greene (2557 pitches)
Gathering Player Data
Success: ranger suarez (4231 pitches)
Gathering Player Data
Success: nick pivetta (3661 pitches)
Gathering Player Data
Success: merrill kelly (4974 pitches)
Gathering Player Data
Success: shane bieber (1516 pitches)
Gathering Player Data
Success: dylan cease (5553 pitches)
Gathering Player Data
Success: jack flaherty (5120 pitches)
Gathering Player Data
Success: kyle bradish (2675 pitches)
Gathering Player Data
Success: bailey ober (4148 pitches)
Gathering Player Data
Success: luis castillo (5447 pitches)
Gathering Player Data
Success: emmanuel clase (868 pitches)
Gathering Player Data
Success: aroldis chapman (1772 pitches)
Gathering Player Data
Success: camilo doval (2010 pitches)
Gathering Player Data
Success: pete fairbanks (1776 pitches)
Gathering Player Data
Success: josh hader (1327 pitches)
Gathering Player Data
Success: devin williams (2004 pitches)
Gathering Player Data
Success: ryan helsley (1472 pitches)
Gathering Player Data
Success: mason miller (1934 pitches)
Gathering Player Data
Success: robert suarez (1799 pitches)
Gathering Player Data
Success: kirby yates (1360 pitches)
Gathering Player Data
Success: shohei ohtani (2571 pitches)
Gathering Player Data
Success: josé berríos (3049 pitches)
Gathering Player Data
Success: cristopher sánchez (5498 pitches)
Gathering Player Data
Success: edwin díaz (1342 pitches)
Gathering Player Data
Success: félix bautista (736 pitches)
Gathering Player Data
Success: andrés muñoz (1998 pitches)
Gathering Player Data
Success: jhoan durán (1952 pitches)

In [5]:
combined_data = pd.concat(all_data, ignore_index=True)
combined_data['player_name'].nunique()

50

In [6]:
combined_data.to_csv('data/raw/pitchers_2025_2026.csv', index=False)

OSError: Cannot save file into a non-existent directory: 'data/raw'

In [7]:
combined_data.to_csv('data/raw/pitchers_2025_2026.csv', index=False)

In [8]:
combined_data.describe()

,release_speed,release_pos_x,release_pos_z,batter,pitcher,spin_dir,spin_rate_deprecated,break_angle_deprecated,break_length_deprecated,zone,...,batter_days_until_next_game,api_break_z_with_gravity,api_break_x_arm,api_break_x_batter_in,arm_angle,attack_angle,attack_direction,swing_path_tilt,intercept_ball_minus_batter_pos_x_inches,intercept_ball_minus_batter_pos_y_inches
count,163617.000000,163616.000000,163616.000000,166413.000000,166413.000000,0.0,0.0,0.0,0.0,163606.000000,...,149218.000000,163615.000000,163615.000000,163615.000000,150409.000000,72081.000000,72081.000000,72073.000000,71947.000000,71947.000000
mean,89.865516,-1.032781,5.706769,659483.869499,633721.014602,NaN,NaN,NaN,NaN,9.163252,...,1.640084,2.350851,0.374627,-0.112185,35.963972,9.480483,-1.733439,32.585824,36.902411,30.405252
std,6.188829,1.741146,0.475547,51626.197806,58806.250645,NaN,NaN,NaN,NaN,4.218967,...,3.221809,1.137115,0.852615,0.924507,12.734578,12.054452,21.216375,7.098934,7.101747,11.951369
min,21.700000,-4.160000,4.340000,455117.000000,489446.000000,NaN,NaN,NaN,NaN,1.000000,...,0.000000,0.220000,-2.300000,-2.760000,-0.400000,-86.857623,-179.871805,0.755153,6.310630,-11.478939
25%,85.300000,-2.200000,5.380000,645444.000000,605483.000000,NaN,NaN,NaN,NaN,5.000000,...,1.000000,1.360000,-0.280000,-0.930000,26.100000,2.136381,-14.254090,27.953185,32.056288,22.232763
50%,90.800000,-1.690000,5.720000,668930.000000,642585.000000,NaN,NaN,NaN,NaN,11.000000,...,1.000000,2.220000,0.530000,-0.180000,36.700000,9.828011,-0.855793,32.546488,36.888714,29.601906
75%,94.900000,-0.460000,6.030000,682653.000000,666808.000000,NaN,NaN,NaN,NaN,13.000000,...,2.000000,3.020000,1.110000,0.680000,45.000000,17.538678,11.479219,37.208549,41.718975,38.288811
max,104.500000,3.590000,7.460000,829712.000000,808967.000000,NaN,NaN,NaN,NaN,14.000000,...,139.000000,8.050000,2.760000,2.480000,79.300000,88.502205,179.201994,89.710476,77.726864,71.978447

In [1]:
from pybaseball import statcast_pitcher, playerid_lookup

In [2]:
import pandas as pd

In [3]:
combined_data = pd.read_csv('data/raw/pitchers_2025_2026.csv')

In [4]:
combined_data.shape

(166413, 119)

In [5]:
combined_data.describe()

,release_speed,release_pos_x,release_pos_z,batter,pitcher,spin_dir,spin_rate_deprecated,break_angle_deprecated,break_length_deprecated,zone,...,batter_days_until_next_game,api_break_z_with_gravity,api_break_x_arm,api_break_x_batter_in,arm_angle,attack_angle,attack_direction,swing_path_tilt,intercept_ball_minus_batter_pos_x_inches,intercept_ball_minus_batter_pos_y_inches
count,163617.000000,163616.000000,163616.000000,166413.000000,166413.000000,0.0,0.0,0.0,0.0,163606.000000,...,149218.000000,163615.000000,163615.000000,163615.000000,150409.000000,72081.000000,72081.000000,72073.000000,71947.000000,71947.000000
mean,89.865516,-1.032781,5.706769,659483.869499,633721.014602,NaN,NaN,NaN,NaN,9.163252,...,1.640084,2.350851,0.374627,-0.112185,35.963972,9.480483,-1.733439,32.585824,36.902411,30.405252
std,6.188829,1.741146,0.475547,51626.197806,58806.250645,NaN,NaN,NaN,NaN,4.218967,...,3.221809,1.137115,0.852615,0.924507,12.734578,12.054452,21.216375,7.098934,7.101747,11.951369
min,21.700000,-4.160000,4.340000,455117.000000,489446.000000,NaN,NaN,NaN,NaN,1.000000,...,0.000000,0.220000,-2.300000,-2.760000,-0.400000,-86.857623,-179.871805,0.755153,6.310630,-11.478939
25%,85.300000,-2.200000,5.380000,645444.000000,605483.000000,NaN,NaN,NaN,NaN,5.000000,...,1.000000,1.360000,-0.280000,-0.930000,26.100000,2.136381,-14.254090,27.953185,32.056288,22.232763
50%,90.800000,-1.690000,5.720000,668930.000000,642585.000000,NaN,NaN,NaN,NaN,11.000000,...,1.000000,2.220000,0.530000,-0.180000,36.700000,9.828011,-0.855793,32.546488,36.888714,29.601906
75%,94.900000,-0.460000,6.030000,682653.000000,666808.000000,NaN,NaN,NaN,NaN,13.000000,...,2.000000,3.020000,1.110000,0.680000,45.000000,17.538678,11.479219,37.208549,41.718975,38.288811
max,104.500000,3.590000,7.460000,829712.000000,808967.000000,NaN,NaN,NaN,NaN,14.000000,...,139.000000,8.050000,2.760000,2.480000,79.300000,88.502205,179.201994,89.710476,77.726864,71.978447

In [6]:
combined_data['pitch_type'].value_counts()

pitch_type
FF    52389
SI    24228
SL    22863
CH    19650
FC    11279
CU    11174
ST     7825
FS     7670
KC     5158
SV     1045
CS      309
PO       10
UN        6
Name: count, dtype: int64

In [7]:
from features import select_direct_features

In [8]:
test_result = select_direct_features(combined_data)
test_result.head()

,balls,strikes,outs_when_up,inning,on_1b,on_2b,on_3b,stand,p_throws,bat_score_diff,n_thruorder_pitcher,n_priorpa_thisgame_player_at_bat,pitch_number,sz_top,sz_bot,pitcher_days_since_prev_game,pitcher_days_until_next_game,pitcher,fielder_2
0,2,2,2,6,True,False,False,L,R,-3,3,2,5,3.284072,1.657382,6.0,5.0,543037,669224
1,1,2,2,6,True,False,False,L,R,-3,3,2,4,3.284072,1.657382,6.0,5.0,543037,669224
2,0,2,2,6,True,False,False,L,R,-3,3,2,3,3.284072,1.657382,6.0,5.0,543037,669224
3,0,1,2,6,True,False,False,L,R,-3,3,2,2,3.284072,1.657382,6.0,5.0,543037,669224
4,0,0,2,6,True,False,False,L,R,-3,3,2,1,3.284072,1.657382,6.0,5.0,543037,669224

In [9]:
test_result.shape

(166413, 19)

In [10]:
test_result.dtypes

balls                                 int64
strikes                               int64
outs_when_up                          int64
inning                                int64
on_1b                                  bool
on_2b                                  bool
on_3b                                  bool
stand                                   str
p_throws                                str
bat_score_diff                        int64
n_thruorder_pitcher                   int64
n_priorpa_thisgame_player_at_bat      int64
pitch_number                          int64
sz_top                              float64
sz_bot                              float64
pitcher_days_since_prev_game        float64
pitcher_days_until_next_game        float64
pitcher                               int64
fielder_2                             int64
dtype: object

In [11]:
test_result[['on_1b', 'on_2b', 'on_3b']].head(10)

   on_1b  on_2b  on_3b
0   True  False  False
1   True  False  False
2   True  False  False
3   True  False  False
4   True  False  False
5  False  False  False
6  False  False  False
7  False  False  False
8  False  False  False
9  False  False  False

In [12]:
combined_data.shape

(166413, 119)

In [13]:
from features import add_previous_pitch_features
test2 = add_previous_pitch_features(combined_data)
test2[['game_pk', 'at_bat_number', 'pitch_number', 'pitch_type', 'prev_pitch_1', 'prev_pitch_2', 'prev_pitch_3']].head(15)

ImportError: cannot import name 'add_previous_pitch_features' from 'features' (/Users/aaravmehta/Downloads/baseball-pitch-predictor/features.py)

In [14]:
from features import add_previous_pitch_features

ImportError: cannot import name 'add_previous_pitch_features' from 'features' (/Users/aaravmehta/Downloads/baseball-pitch-predictor/features.py)

In [15]:
from features import add_previous_pitch_features

ImportError: cannot import name 'add_previous_pitch_features' from 'features' (/Users/aaravmehta/Downloads/baseball-pitch-predictor/features.py)

In [16]:
import importlib
import features
importlib.reload(features)
from features import add_previous_pitch_features

In [17]:
test2 = add_previous_pitch_features(combined_data)
test2[['game_pk', 'at_bat_number', 'pitch_number', 'pitch_type', 'prev_pitch_1', 'prev_pitch_2', 'prev_pitch_3']].head(15)

,game_pk,at_bat_number,pitch_number,pitch_type,prev_pitch_1,prev_pitch_2,prev_pitch_3
20364,776137,1,1,FC,NaN,NaN,NaN
20363,776137,1,2,SI,FC,NaN,NaN
20362,776137,1,3,FF,SI,FC,NaN
20361,776137,1,4,ST,FF,SI,FC
20360,776137,2,1,CH,NaN,NaN,NaN
20359,776137,2,2,SI,CH,NaN,NaN
20358,776137,2,3,ST,SI,CH,NaN
20357,776137,2,4,SI,ST,SI,CH
20356,776137,2,5,FF,SI,ST,SI
20355,776137,3,1,SI,NaN,NaN,NaN
20354,776137,3,2,ST,SI,NaN,NaN
20353,776137,3,3,CH,ST,SI,NaN
20352,776137,3,4,CH,CH,ST,SI
20351,776137,8,1,CH,NaN,NaN,NaN
20350,776137,8,2,CH,CH,NaN,NaN

In [18]:
from features import add_rolling_velocity

test3 = add_rolling_velocity(combined_data)
test3[['pitcher', 'game_pk', 'at_bat_number', 'pitch_number', 'release_speed', 'rolling_velocity']].head(15)

ImportError: cannot import name 'add_rolling_velocity' from 'features' (/Users/aaravmehta/Downloads/baseball-pitch-predictor/features.py)

In [19]:
import importlib
import features
importlib.reload(features)
from features import add_rolling_velocity

test3 = add_rolling_velocity(combined_data)
test3[['pitcher', 'game_pk', 'at_bat_number', 'pitch_number', 'release_speed', 'rolling_velocity']].head(15)

Try

NameError: name 'Try' is not defined

In [20]:
import importlib
import features
importlib.reload(features)
from features import add_rolling_velocity

In [21]:
test3 = add_rolling_velocity(combined_data)
test3[['pitcher', 'game_pk', 'at_bat_number', 'pitch_number', 'release_speed', 'rolling_velocity']].head(15)

,pitcher,game_pk,at_bat_number,pitch_number,release_speed,rolling_velocity
20364,657277,776137,1,1,90.9,NaN
20363,657277,776137,1,2,93.4,90.90
20362,657277,776137,1,3,93.2,92.15
20361,657277,776137,1,4,84.9,92.50
20360,657277,776137,2,1,86.6,90.60
20359,657277,776137,2,2,94.1,89.80
20358,657277,776137,2,3,85.3,90.44
20357,657277,776137,2,4,93.3,88.82
20356,657277,776137,2,5,94.5,88.84
20355,657277,776137,3,1,93.6,90.76
20354,657277,776137,3,2,87.0,92.16
20353,657277,776137,3,3,87.3,90.74
20352,657277,776137,3,4,87.3,91.14
20351,657277,776137,8,1,84.8,89.94
20350,657277,776137,8,2,85.4,88.00

In [22]:
import importlib
import features
importlib.reload(features)
from features import add_rolling_pitch_mix

In [23]:
test4 = add_rolling_pitch_mix(combined_data)

NameError: name 'pd' is not defined

In [24]:
import importlib
import features
importlib.reload(features)
from features import add_rolling_pitch_mix

In [25]:
test4 = add_rolling_pitch_mix(combined_data)

TypeError: cumsum is not supported for object dtype

In [26]:
importlib.reload(features)
from features import add_rolling_pitch_mix

test4 = add_rolling_pitch_mix(combined_data)

In [27]:
[col for col in test4.columns if col.startswith('pct_')]

['pct_CH_so_far',
 'pct_CS_so_far',
 'pct_CU_so_far',
 'pct_FC_so_far',
 'pct_FF_so_far',
 'pct_FS_so_far',
 'pct_KC_so_far',
 'pct_PO_so_far',
 'pct_SI_so_far',
 'pct_SL_so_far',
 'pct_ST_so_far',
 'pct_SV_so_far',
 'pct_UN_so_far']

In [28]:
test4[test4['pitcher'] == 657277][['game_pk', 'pitch_number', 'pitch_type', 'pct_FF_so_far', 'pct_SI_so_far']].head(15)

       game_pk  pitch_number pitch_type  pct_FF_so_far  pct_SI_so_far
20364   776137             1         FC       0.000000       0.000000
20363   776137             2         SI       0.000000       0.000000
20362   776137             3         FF       0.000000       0.500000
20361   776137             4         ST       0.333333       0.333333
20360   776137             1         CH       0.250000       0.250000
20359   776137             2         SI       0.200000       0.200000
20358   776137             3         ST       0.166667       0.333333
20357   776137             4         SI       0.142857       0.285714
20356   776137             5         FF       0.125000       0.375000
20355   776137             1         SI       0.222222       0.333333
20354   776137             2         ST       0.200000       0.400000
20353   776137             3         CH       0.181818       0.363636
20352   776137             4         CH       0.166667       0.333333
20351   776137             1         CH       0.153846       0.307692
20350   776137             2         CH       0.142857       0.285714

In [29]:
pct_cols = [col for col in test4.columns if col.startswith('pct_')]
test4[pct_cols].sum(axis=1).describe()

count    166413.000000
mean          0.964925
std           0.180462
min           0.000000
25%           1.000000
50%           1.000000
75%           1.000000
max           1.000000
dtype: float64

In [30]:
test4[test4['pitch_number'] == 1][pct_cols].sum(axis=1).describe()

count    42590.000000
mean         0.912610
std          0.280309
min          0.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          1.000000
dtype: float64

In [31]:
importlib.reload(features)
from features import add_pitch_effectiveness

SyntaxError: unterminated string literal (detected at line 58) (features.py, line 58)

In [32]:
importlib.reload(features)
from features import add_pitch_effectiveness

In [33]:
test5 = add_pitch_effectiveness(combined_data)
[col for col in test5.columns if col.startswith('whiff_rate_')]

['whiff_rate_FC_so_far',
 'whiff_rate_SI_so_far',
 'whiff_rate_FF_so_far',
 'whiff_rate_ST_so_far',
 'whiff_rate_CH_so_far',
 'whiff_rate_FS_so_far',
 'whiff_rate_SL_so_far',
 'whiff_rate_KC_so_far',
 'whiff_rate_CU_so_far',
 'whiff_rate_CS_so_far',
 'whiff_rate_SV_so_far',
 'whiff_rate_PO_so_far',
 'whiff_rate_UN_so_far']

In [34]:
test5[test5['pitcher'] == 657277][['game_pk', 'pitch_number', 'pitch_type', 'description', 'whiff_rate_FF_so_far']].head(20)

       game_pk  pitch_number pitch_type      description  whiff_rate_FF_so_far
20364   776137             1         FC             ball                   0.0
20363   776137             2         SI             foul                   0.0
20362   776137             3         FF  swinging_strike                   0.0
20361   776137             4         ST  swinging_strike                   1.0
20360   776137             1         CH             ball                   1.0
20359   776137             2         SI             ball                   1.0
20358   776137             3         ST    called_strike                   1.0
20357   776137             4         SI  swinging_strike                   1.0
20356   776137             5         FF  swinging_strike                   1.0
20355   776137             1         SI    called_strike                   1.0
20354   776137             2         ST             foul                   1.0
20353   776137             3         CH             ball                   1.0
20352   776137             4         CH  swinging_strike                   1.0
20351   776137             1         CH             ball                   1.0
20350   776137             2         CH  swinging_strike                   1.0
20349   776137             3         SI             ball                   1.0
20348   776137             4         CH    hit_into_play                   1.0
20347   776137             1         SI    called_strike                   1.0
20346   776137             2         ST             ball                   1.0
20345   776137             3         SI    hit_into_play                   1.0

In [35]:
test5[test5['pitcher'] == 657277][['game_date', 'pitch_number', 'pitch_type', 'description', 'whiff_rate_FF_so_far']].tail(20)

,game_date,pitch_number,pitch_type,description,whiff_rate_FF_so_far
20280,2026-02-24,3,FF,called_strike,1.000000
20279,2026-02-24,4,ST,foul,0.500000
20278,2026-02-24,5,CH,ball,0.500000
20277,2026-02-24,6,ST,hit_into_play,0.500000
20276,2026-02-24,1,CH,called_strike,0.500000
20275,2026-02-24,2,FC,called_strike,0.500000
20274,2026-02-24,3,CH,ball,0.500000
20273,2026-02-24,4,SI,ball,0.500000
20272,2026-02-24,5,ST,ball,0.500000
20271,2026-02-24,6,ST,swinging_strike,0.500000
20270,2026-02-24,1,SI,called_strike,0.500000
20269,2026-02-24,2,CH,swinging_strike,0.500000
20268,2026-02-24,3,CH,swinging_strike,0.500000
20267,2026-02-24,1,SI,ball,0.500000
20266,2026-02-24,2,SI,called_strike,0.500000
20265,2026-02-24,3,FF,hit_into_play,0.500000
20264,2026-02-24,1,ST,ball,0.333333
20263,2026-02-24,2,ST,swinging_strike,0.333333
20262,2026-02-24,3,ST,called_strike,0.333333
20261,2026-02-24,4,SI,called_strike,0.333333

In [37]:
importlib.reload(features)
from features import add_season_pitch_mix

In [38]:
test6 = add_season_pitch_mix(combined_data)

In [39]:
test6[test6['pitcher'] == 657277][['pitcher', 'pitch_type', 'season_pct_FF', 'season_pct_SI']].head(5)

       pitcher pitch_type  season_pct_FF  season_pct_SI
18444   657277         SI       0.089414       0.311657
18445   657277         SI       0.089414       0.311657
18446   657277         CH       0.089414       0.311657
18447   657277         CH       0.089414       0.311657
18448   657277         FC       0.089414       0.311657

In [40]:
importlib.reload(features)
from features import add_pitcher_role

In [41]:
test7 = add_pitcher_role(combined_data)

In [42]:
test7.groupby('player_name')[['avg_pitches_per_game', 'is_starter']].first().sort_values('avg_pitches_per_game')

                     avg_pitches_per_game  is_starter
player_name
Chapman, Aroldis                14.766667           0
Yates, Kirby                    15.111111           0
Duran, Jhoan                    15.250000           0
Suarez, Robert                  15.643478           0
Clase, Emmanuel                 15.781818           0
Doval, Camilo                   15.952381           0
Muñoz, Andrés                   16.112903           0
Fairbanks, Pete                 16.444444           0
Miller, Mason                   16.529915           0
Helsley, Ryan                   16.539326           0
Hader, Josh                     16.797468           0
Williams, Devin                 16.983051           0
Díaz, Edwin                     17.428571           0
Bautista, Félix                 17.951220           0
Dunning, Dane                   35.900000           0
Glasnow, Tyler                  73.153846           1
Cole, Gerrit                    75.187500           1
Ohtani, Shohei                  75.617647           1
Burnes, Corbin                  76.470588           1
Miller, Bryce                   78.000000           1
Berríos, José                   78.179487           1
Bieber, Shane                   79.789474           1
Lorenzen, Michael               80.155172           1
Gray, Sonny                     81.186441           1
Ober, Bailey                    81.333333           1
Greene, Hunter                  82.483871           1
Pivetta, Nick                   83.204545           1
Strider, Spencer                83.750000           1
Castillo, Luis                  83.800000           1
Flaherty, Jack                  83.934426           1
Kelly, Merrill                  84.305085           1
Suarez, Ranger                  84.620000           1
Nola, Aaron                     85.173913           1
Lugo, Seth                      85.553571           1
Gallen, Zac                     85.600000           1
Skubal, Tarik                   85.724138           1
Valdez, Framber                 86.049180           1
Bradish, Kyle                   86.290323           1
Snell, Blake                    87.200000           1
Sánchez, Cristopher             87.269841           1
Sale, Chris                     87.860000           1
Gausman, Kevin                  88.469697           1
Crochet, Garrett                89.291667           1
Yamamoto, Yoshinobu             89.322581           1
Skenes, Paul                    89.491803           1
Peralta, Freddy                 89.553846           1
Fried, Max                      90.150943           1
Webb, Logan                     90.216667           1
Cease, Dylan                    92.550000           1
Wheeler, Zack                   94.088889           1