In [6]:
from pybaseball import statcast_pitcher, playerid_lookup
player = playerid_lookup('webb','logan')

In [7]:
import pandas as pd

In [4]:
player

,name_last,name_first,key_mlbam,key_retro,key_bbref,key_fangraphs,mlb_played_first,mlb_played_last
0,webb,logan,657277,webbl001,webblo01,17995,2019.0,2026.0

In [5]:
combined_data.shape

NameError: name 'combined_data' is not defined

In [ ]:
df = pd.DataFrame(combined_data)
column_list = df.columns
print(f"There are {len(column_list)} columns and the first ten are {column_list[:20]}")
print(f"Events is {df['game_type'][:5]}")

In [ ]:
pitcher_id = playerid_lookup('crochet', ['key_mlbam'].iloc[0]

In [ ]:
combined_data['player_name'].unique()

In [ ]:
combined_data.groupby('player_name').size()

In [ ]:
combined_data['pitch_type'].value_counts()

In [ ]:
combined_data['release_speed'].describe()

In [ ]:
pitchers = [
    ('webb', 'logan'),
    ('lorenzen', 'michael'),
    ('yamamoto', 'yoshinobu'),
    ('gausman', 'kevin'),
    ('skenes', 'paul'),
    ('skubal', 'tarik'),
    ('chapman', 'aroldis'),
    ('doval', 'camilo'),
    ('crochet', 'garrett'),
    ('glasnow', 'tyler'),
]

all_data = []

for last_name, first_name in pitchers:
    lookup = playerid_lookup(last_name, first_name)
    pid = lookup['key_mlbam'].iloc[0]
    pitcher_data = statcast_pitcher('2025-04-01', '2025-10-31', pid)
    all_data.append(pitcher_data)

combined_data = pd.concat(all_data, ignore_index=True)

In [ ]:
combined_data[combined_data['release_speed'] <= 65]

In [ ]:
combined_data.isnull().sum().sort_values(ascending=False).head(10)

In [ ]:
pitcher_id

In [ ]:
data = statcast_pitcher('2024-04-01', '2024-04-30', pitcher_id)

In [ ]:
data_full_season = statcast_pitcher('2024-04-01', '2024-09-30', pitcher_id)

In [ ]:
data_full_season.shape

In [ ]:
data.shape

In [ ]:
data_full_season.head()

In [ ]:
data.head()

In [ ]:
pitchers = [
    ('webb', 'logan'),
    ('lorenzen', 'michael'),
    ('yamamoto', 'yoshinobu'),
    ('gausman', 'kevin'),
    ('skenes', 'paul'),
    ('skubal', 'tarik'),
    ('chapman', 'aroldis'),
    ('doval', 'camilo'),
    ('crochet', 'garrett'),
    ('glasnow', 'tyler'),
]

all_data = []

for last_name, first_name in pitchers:
    lookup = playerid_lookup(last_name, first_name)
    pid = lookup['key_mlbam'].iloc[0]
    pitcher_data = statcast_pitcher('2025-04-01', '2025-10-31', pid)
    all_data.append(pitcher_data)

combined_data = pd.concat(all_data, ignore_index=True)

print(combined_data.shape)
print(combined_data['player_name'].unique())
print(combined_data.groupby('player_name').size())

In [ ]:
combined_data.columns.tolist()

In [ ]:
combined_data.to_csv('combined_data_preview.csv', index=False)

In [8]:
pitchers = [
    ('cole', 'gerrit'), ('wheeler', 'zack'), ('strider', 'spencer'), ('burnes', 'corbin'),
    ('gausman', 'kevin'), ('glasnow', 'tyler'), ('webb', 'logan'), ('valdez', 'framber'),
    ('yamamoto', 'yoshinobu'), ('skenes', 'paul'), ('skubal', 'tarik'), ('crochet', 'garrett'),
    ('lorenzen', 'michael'), ('dunning', 'dane'), ('lugo', 'seth'), ('sale', 'chris'),
    ('peralta', 'freddy'), ('nola', 'aaron'), ('gray', 'sonny'), ('snell', 'blake'),
    ('gallen', 'zac'), ('fried', 'max'), ('miller', 'bryce'), ('greene', 'hunter'),
    ('suarez', 'ranger'), ('pivetta', 'nick'), ('berrios', 'jose'), ('kelly', 'merrill'),
    ('morton', 'charlie'), ('bieber', 'shane'), ('cease', 'dylan'), ('flaherty', 'jack'),
    ('bradish', 'kyle'), ('ober', 'bailey'), ('sanchez', 'cristopher'),
    ('clase', 'emmanuel'), ('chapman', 'aroldis'), ('doval', 'camilo'), ('fairbanks', 'pete'),
    ('hader', 'josh'), ('diaz', 'edwin'), ('williams', 'devin'), ('bautista', 'felix'),
    ('helsley', 'ryan'), ('miller', 'mason'), ('suarez', 'robert'), ('munoz', 'andres'),
    ('yates', 'kirby'), ('duran', 'jhoan'), ('ohtani', 'shohei'),
]

start_date = '2025-01-01'
end_date = '2026-07-28'

all_data = []
failed_pitchers = []

for last_name, first_name in pitchers:
    try:
        lookup = playerid_lookup(last_name, first_name)
        pid = lookup['key_mlbam'].iloc[0]
        pitcher_data = statcast_pitcher(start_date, end_date, pid)
        all_data.append(pitcher_data)
        print(f"Success: {first_name} {last_name} ({len(pitcher_data)} pitches)")
    except Exception as e:
        print(f"FAILED: {first_name} {last_name} - {e}")
        failed_pitchers.append((last_name, first_name))

combined_data = pd.concat(all_data, ignore_index=True)

Gathering Player Data
Success: gerrit cole (1203 pitches)
Gathering Player Data
Success: zack wheeler (4234 pitches)
Gathering Player Data
Success: spencer strider (3015 pitches)
Gathering Player Data
Success: corbin burnes (1300 pitches)
Gathering Player Data
Success: kevin gausman (5839 pitches)
Gathering Player Data
Success: tyler glasnow (2853 pitches)
Gathering Player Data
Success: logan webb (5413 pitches)
Gathering Player Data
Success: framber valdez (5249 pitches)
Gathering Player Data
Success: yoshinobu yamamoto (5538 pitches)
Gathering Player Data
Success: paul skenes (5459 pitches)
Gathering Player Data
Success: tarik skubal (4972 pitches)
Gathering Player Data
Success: garrett crochet (4286 pitches)
Gathering Player Data
Success: michael lorenzen (4649 pitches)
Gathering Player Data
Success: dane dunning (718 pitches)
Gathering Player Data
Success: seth lugo (4791 pitches)
Gathering Player Data
Success: chris sale (4393 pitches)
Gathering Player Data
Success: freddy peralta (5821 pitches)
Gathering Player Data
Success: aaron nola (3918 pitches)
Gathering Player Data
Success: sonny gray (4790 pitches)
Gathering Player Data
Success: blake snell (1744 pitches)
Gathering Player Data
Success: zac gallen (5136 pitches)
Gathering Player Data
Success: max fried (4778 pitches)
Gathering Player Data
Success: bryce miller (2964 pitches)
Gathering Player Data
Success: hunter greene (2557 pitches)
Gathering Player Data
Success: ranger suarez (4231 pitches)
Gathering Player Data
Success: nick pivetta (3661 pitches)
FAILED: jose berrios - single positional indexer is out-of-bounds
Gathering Player Data
Success: merrill kelly (4974 pitches)
Gathering Player Data
Success: charlie morton (0 pitches)
Gathering Player Data
Success: shane bieber (1516 pitches)
Gathering Player Data
Success: dylan cease (5553 pitches)
Gathering Player Data
Success: jack flaherty (5120 pitches)
Gathering Player Data
Success: kyle bradish (2675 pitches)
Gathering Player Data
Success: bailey ober (4148 pitches)
FAILED: cristopher sanchez - single positional indexer is out-of-bounds
Gathering Player Data
Success: emmanuel clase (868 pitches)
Gathering Player Data
Success: aroldis chapman (1772 pitches)
Gathering Player Data
Success: camilo doval (2010 pitches)
Gathering Player Data
Success: pete fairbanks (1776 pitches)
Gathering Player Data
Success: josh hader (1327 pitches)
FAILED: edwin diaz - single positional indexer is out-of-bounds
Gathering Player Data
Success: devin williams (2004 pitches)
FAILED: felix bautista - single positional indexer is out-of-bounds
Gathering Player Data
Success: ryan helsley (1472 pitches)
Gathering Player Data
Success: mason miller (1934 pitches)
Gathering Player Data
Success: robert suarez (1799 pitches)
FAILED: andres munoz - single positional indexer is out-of-bounds
Gathering Player Data
Success: kirby yates (1360 pitches)
FAILED: jhoan duran - single positional indexer is out-of-bounds
Gathering Player Data
Success: shohei ohtani (2571 pitches)

In [9]:
len(all_data)

44

In [10]:
all_data = [df for df in all_data if len(df) > 0]

In [11]:
new_pitchers = [
    ('castillo', 'luis'),
    ('berríos', 'josé'),
    ('sánchez', 'cristopher'),
    ('díaz', 'edwin'),
    ('bautista', 'félix'),
    ('muñoz', 'andrés'),
    ('durán', 'jhoan'),
]

for last_name, first_name in new_pitchers:
    try:
        lookup = playerid_lookup(last_name, first_name)
        pid = lookup['key_mlbam'].iloc[0]
        pitcher_data = statcast_pitcher(start_date, end_date, pid)
        all_data.append(pitcher_data)
        print(f"Success: {first_name} {last_name} ({len(pitcher_data)} pitches)")
    except Exception as e:
        print(f"FAILED: {first_name} {last_name} - {e}")
        failed_pitchers.append((last_name, first_name))

combined_data = pd.concat(all_data, ignore_index=True)

Gathering Player Data
Success: luis castillo (0 pitches)
Gathering Player Data
Success: josé berríos (3049 pitches)
Gathering Player Data
Success: cristopher sánchez (5498 pitches)
Gathering Player Data
Success: edwin díaz (1342 pitches)
Gathering Player Data
Success: félix bautista (736 pitches)
Gathering Player Data
Success: andrés muñoz (1998 pitches)
Gathering Player Data
Success: jhoan durán (1952 pitches)

In [12]:
playerid_lookup('castillo', 'luis')

,name_last,name_first,key_mlbam,key_retro,key_bbref,key_fangraphs,mlb_played_first,mlb_played_last
0,castillo,luis,112116,castl001,castilu01,513,1996.0,2010.0
1,castillo,luis,622379,castl004,castilu03,20638,2022.0,2025.0
2,castillo,luis,622491,castl003,castilu02,15689,2017.0,2026.0

In [13]:
castillo_data = statcast_pitcher(start_date, end_date, 622491)
all_data.append(castillo_data)
print(f"Success: luis castillo ({len(castillo_data)} pitches)")

Gathering Player Data
Success: luis castillo (5447 pitches)

In [14]:
combined_data = pd.concat(all_data, ignore_index=True)

In [15]:
combined_data['player_name'].nunique()

50

In [16]:
combined_data.groupby('player_name').size()

player_name
Bautista, Félix         736
Berríos, José          3049
Bieber, Shane          1516
Bradish, Kyle          2675
Burnes, Corbin         1300
Castillo, Luis         5447
Cease, Dylan           5553
Chapman, Aroldis       1772
Clase, Emmanuel         868
Cole, Gerrit           1203
Crochet, Garrett       4286
Doval, Camilo          2010
Dunning, Dane           718
Duran, Jhoan           1952
Díaz, Edwin            1342
Fairbanks, Pete        1776
Flaherty, Jack         5120
Fried, Max             4778
Gallen, Zac            5136
Gausman, Kevin         5839
Glasnow, Tyler         2853
Gray, Sonny            4790
Greene, Hunter         2557
Hader, Josh            1327
Helsley, Ryan          1472
Kelly, Merrill         4974
Lorenzen, Michael      4649
Lugo, Seth             4791
Miller, Bryce          2964
Miller, Mason          1934
Muñoz, Andrés          1998
Nola, Aaron            3918
Ober, Bailey           4148
Ohtani, Shohei         2571
Peralta, Freddy        5821
Pivetta, Nick          3661
Sale, Chris            4393
Skenes, Paul           5459
Skubal, Tarik          4972
Snell, Blake           1744
Strider, Spencer       3015
Suarez, Ranger         4231
Suarez, Robert         1799
Sánchez, Cristopher    5498
Valdez, Framber        5249
Webb, Logan            5413
Wheeler, Zack          4234
Williams, Devin        2004
Yamamoto, Yoshinobu    5538
Yates, Kirby           1360
dtype: int64

In [17]:
playerid_lookup('morton', 'charlie')

,name_last,name_first,key_mlbam,key_retro,key_bbref,key_fangraphs,mlb_played_first,mlb_played_last
0,morton,charlie,119424,mortc101,mortoch01,1009231,1882.0,1885.0
1,morton,charlie,450203,mortc002,mortoch02,4676,2008.0,2025.0

In [18]:
combined_data = pd.concat(all_data, ignore_index=True)
combined_data['player_name'].nunique()

50

In [19]:
combined_data.to_csv('data/raw/pitchers_2025_2026.csv', index=False)

OSError: Cannot save file into a non-existent directory: 'data/raw'

In [20]:
combined_data.to_csv('data/raw/pitchers_2025_2026.csv', index=False)

In [1]:
from pybaseball import statcast_pitcher, playerid_lookup

In [2]:
import pandas as pd

In [3]:
combined_data = pd.read_csv('data/raw/pitchers_2025_2026.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'data/raw/pitchers_2025_2026.csv'

In [4]:
pitchers = [
    ('cole', 'gerrit'), ('wheeler', 'zack'), ('strider', 'spencer'), ('burnes', 'corbin'),
    ('gausman', 'kevin'), ('glasnow', 'tyler'), ('webb', 'logan'), ('valdez', 'framber'),
    ('yamamoto', 'yoshinobu'), ('skenes', 'paul'), ('skubal', 'tarik'), ('crochet', 'garrett'),
    ('lorenzen', 'michael'), ('dunning', 'dane'), ('lugo', 'seth'), ('sale', 'chris'),
    ('peralta', 'freddy'), ('nola', 'aaron'), ('gray', 'sonny'), ('snell', 'blake'),
    ('gallen', 'zac'), ('fried', 'max'), ('miller', 'bryce'), ('greene', 'hunter'),
    ('suarez', 'ranger'), ('pivetta', 'nick'), ('kelly', 'merrill'),
    ('bieber', 'shane'), ('cease', 'dylan'), ('flaherty', 'jack'),
    ('bradish', 'kyle'), ('ober', 'bailey'), ('castillo', 'luis'),
    ('clase', 'emmanuel'), ('chapman', 'aroldis'), ('doval', 'camilo'), ('fairbanks', 'pete'),
    ('hader', 'josh'), ('williams', 'devin'),
    ('helsley', 'ryan'), ('miller', 'mason'), ('suarez', 'robert'),
    ('yates', 'kirby'), ('ohtani', 'shohei'),
    ('berríos', 'josé'), ('sánchez', 'cristopher'), ('díaz', 'edwin'),
    ('bautista', 'félix'), ('muñoz', 'andrés'), ('durán', 'jhoan'),
]

start_date = '2025-01-01'
end_date = '2026-07-28'

all_data = []
failed_pitchers = []

for last_name, first_name in pitchers:
    try:
        if last_name == 'castillo':
            pid = 622491  # hardcoded — fixes duplicate-name collision found earlier
        else:
            lookup = playerid_lookup(last_name, first_name)
            pid = lookup['key_mlbam'].iloc[0]
        pitcher_data = statcast_pitcher(start_date, end_date, pid)
        all_data.append(pitcher_data)
        print(f"Success: {first_name} {last_name} ({len(pitcher_data)} pitches)")
    except Exception as e:
        print(f"FAILED: {first_name} {last_name} - {e}")
        failed_pitchers.append((last_name, first_name))

combined_data = pd.concat(all_data, ignore_index=True)

Gathering player lookup table. This may take a moment.
Gathering Player Data
Success: gerrit cole (1203 pitches)
Gathering Player Data
Success: zack wheeler (4234 pitches)
Gathering Player Data
Success: spencer strider (3015 pitches)
Gathering Player Data
Success: corbin burnes (1300 pitches)
Gathering Player Data
Success: kevin gausman (5839 pitches)
Gathering Player Data
Success: tyler glasnow (2853 pitches)
Gathering Player Data
Success: logan webb (5413 pitches)
Gathering Player Data
Success: framber valdez (5249 pitches)
Gathering Player Data
Success: yoshinobu yamamoto (5538 pitches)
Gathering Player Data
Success: paul skenes (5459 pitches)
Gathering Player Data
Success: tarik skubal (4972 pitches)
Gathering Player Data
Success: garrett crochet (4286 pitches)
Gathering Player Data
Success: michael lorenzen (4649 pitches)
Gathering Player Data
Success: dane dunning (718 pitches)
Gathering Player Data
Success: seth lugo (4791 pitches)
Gathering Player Data
Success: chris sale (4393 pitches)
Gathering Player Data
Success: freddy peralta (5821 pitches)
Gathering Player Data
Success: aaron nola (3918 pitches)
Gathering Player Data
Success: sonny gray (4790 pitches)
Gathering Player Data
Success: blake snell (1744 pitches)
Gathering Player Data
Success: zac gallen (5136 pitches)
Gathering Player Data
Success: max fried (4778 pitches)
Gathering Player Data
Success: bryce miller (2964 pitches)
Gathering Player Data
Success: hunter greene (2557 pitches)
Gathering Player Data
Success: ranger suarez (4231 pitches)
Gathering Player Data
Success: nick pivetta (3661 pitches)
Gathering Player Data
Success: merrill kelly (4974 pitches)
Gathering Player Data
Success: shane bieber (1516 pitches)
Gathering Player Data
Success: dylan cease (5553 pitches)
Gathering Player Data
Success: jack flaherty (5120 pitches)
Gathering Player Data
Success: kyle bradish (2675 pitches)
Gathering Player Data
Success: bailey ober (4148 pitches)
Gathering Player Data
Success: luis castillo (5447 pitches)
Gathering Player Data
Success: emmanuel clase (868 pitches)
Gathering Player Data
Success: aroldis chapman (1772 pitches)
Gathering Player Data
Success: camilo doval (2010 pitches)
Gathering Player Data
Success: pete fairbanks (1776 pitches)
Gathering Player Data
Success: josh hader (1327 pitches)
Gathering Player Data
Success: devin williams (2004 pitches)
Gathering Player Data
Success: ryan helsley (1472 pitches)
Gathering Player Data
Success: mason miller (1934 pitches)
Gathering Player Data
Success: robert suarez (1799 pitches)
Gathering Player Data
Success: kirby yates (1360 pitches)
Gathering Player Data
Success: shohei ohtani (2571 pitches)
Gathering Player Data
Success: josé berríos (3049 pitches)
Gathering Player Data
Success: cristopher sánchez (5498 pitches)
Gathering Player Data
Success: edwin díaz (1342 pitches)
Gathering Player Data
Success: félix bautista (736 pitches)
Gathering Player Data
Success: andrés muñoz (1998 pitches)
Gathering Player Data
Success: jhoan durán (1952 pitches)

In [5]:
combined_data = pd.concat(all_data, ignore_index=True)
combined_data['player_name'].nunique()

50

In [6]:
combined_data.to_csv('data/raw/pitchers_2025_2026.csv', index=False)

OSError: Cannot save file into a non-existent directory: 'data/raw'

In [7]:
combined_data.to_csv('data/raw/pitchers_2025_2026.csv', index=False)